<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Commands\CommandHandlers\" />
    <Folder Include="Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.27" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OnlineVoting.Domain\OnlineVoting.Domain.csproj" />
  </ItemGroup>

</Project>
